#!/bin/bash
# Maven Lite post-installation script

mvnlHome="/home/${USER}/.mavenLite"
mvnlFile="MavenLite.class"
mvnlTmp="/tmp"

# Check if Maven Lite is already installed
if [ ! -d ${mvnlHome} ]; then
    mkdir ${mvnlHome}
fi

# déplacement du fichier MavenLite.class dans le répertoire d'installation
mv ${mvnlTmp}/${mvnlFile} ${mvnlHome}/${mvnlFile}