#!/bin/bash

for i in $@; do
    # Si l'argument commence par un backslash, on le double
    if [[ $i =~ ^\\ ]]; then
        args="$args \\$i"
    else
        args="$args $i"
    fi
done

java -cp bin MavenLite $args