#!/bin/sh

#======#
# Main #
#======#
# Constantes
SUCCES="[SUCCES]"
ERROR="[ERREUR]"


# Variables
shellFile="/usr/local/bin/mvnl"
classFile="/etc/maven-lite/MavenLite.class"
uninstaller="/usr/local/bin/mvnl-uninstall"

# Suppression des pages de manuel
mvnl uninstall_from_mvnl-uninstall

exitCode=$?
if [ $exitCode -gt 0 ]; then
    exit $exitCode
fi

# Suppression du fichier shell
sudo rm -f ${shellFile} && echo "${SUCCES} Le fichier '${shellFile}' a été supprimé avec succès." || {
    echo "${ERROR} Erreur lors de la suppression du fichier '${shellFile}'."
    exit 1
}

# Suppression du fichier class
sudo rm -f ${classFile} && echo "${SUCCES} Le fichier '${classFile}' a été supprimé avec succès." || {
    echo "${ERROR} Erreur lors de la suppression du fichier '${classFile}'."
    exit 1
}

# Suppression du fichier uninstaller
sudo rm -f ${uninstaller} && echo "${SUCCES} Le fichier '${uninstaller}' a été supprimé avec succès." || {
    echo "${ERROR} Erreur lors de la suppression du fichier '${uninstaller}'."
    exit 1
}

echo -e "\n${SUCCES} Désinstallation de Maven Lite terminée avec succès."
exit 0