#!/bin/sh

#======#
# Main #
#======#
# Constantes
SUCCES="[SUCCESS]"
ERROR="[ERROR]"


# Variables
shellFile="/usr/local/bin/mvnl"
classFile="/etc/maven-lite/MavenLite.class"
uninstaller="/usr/local/bin/mvnl-uninstall"

# Suppression des pages de manuel
mvnl uninstall_from_mvnl-uninstall

exitCode=$?
if [ $exitCode -gt 0 ]; then
    exit $exitCode
fi

# Suppression du fichier shell
sudo rm -f ${shellFile} && echo "${SUCCES} The file '${shellFile}' has been successfully deleted." || {
    echo "${ERROR} Error occurred while deleting the file '${shellFile}'."
    exit 1
}

# Suppression du fichier class
sudo rm -f ${classFile} && echo "${SUCCES} The file '${classFile}' has been successfully deleted." || {
    echo "${ERROR} Error occurred while deleting the file '${shellFile}'."
    exit 1
}

# Suppression du fichier uninstaller
sudo rm -f ${uninstaller} && echo "${SUCCES} The file '${uninstaller}' has been successfully deleted." || {
    echo "${ERROR} Error occurred while deleting the file '${shellFile}'."
    exit 1
}

echo -e "\n${SUCCES} Uninstallation of Maven Lite completed successfully."
exit 0