#!/bin/bash

# This file is part of Maven Lite.
# Copyright (C) 2024 Floris Robart florisrobart.pro@gmail.com

#======#
# Main #
#======#
# Constantes
SUCCES="[SUCCESS]"
ERROR="[ERROR]"


# Variables
mavenLiteFolder="/usr/local/etc/maven-lite"
shellFile="/usr/local/bin/mvnl"
uninstaller="/usr/local/bin/mvnl-uninstall"

# Demande de confirmation et suppression des pages de manuel
mvnl uninstall_from_mvnl-uninstall

exitCode=$?
if [ $exitCode -gt 0 ]; then
    exit $exitCode
fi

# Suppression du fichier shell
if [ -f ${shellFile} ]; then
    sudo rm -f ${shellFile} || {
        echo "${ERROR} Error occurred during the deletion of the '${shellFile}' file."
        exit 1
    }
fi

# Suppression du dossier maven-lite
if [ -d ${mavenLiteFolder} ]; then
    sudo rm -rf ${mavenLiteFolder} || {
        echo "${ERROR} Error occurred during the deletion of the '${mavenLiteFolder}' folder."
        exit 1
    }
fi

# Suppression du fichier uninstaller
if [ -f ${uninstaller} ]; then
    sudo rm -f ${uninstaller} || {
        echo "${ERROR} Error occurred during the deletion of the '${uninstaller}' file."
        exit 1
    }
fi

echo -e "\n${SUCCES} Maven Lite uninstallation completed successfully."
exit 0